// swift-tools-version:6.0
// Generated by SwiftFlowKit

import PackageDescription

let package = Package(
    name: "NnGoogleAdsKit",
    platforms: [
        .iOS(.v17)
    ],
    products: [
        .library(
            name: "NnGoogleAdsKit",
            targets: ["NnGoogleAdsKit"]
        ),
        
    ],
    dependencies: [
        .package(url: "https://github.com/googleads/swift-package-manager-google-mobile-ads.git", from: "12.0.0")
    ],
    targets: [
        .target(
            name: "NnGoogleAdsKit",
            dependencies: [
                .product(name: "GoogleMobileAds", package: "swift-package-manager-google-mobile-ads")
            ]
        ),
    ]
)
