// swift-tools-version: 6.0
// Generated by SwiftFlowKit

import PackageDescription

let package = Package(
    name: "NnGoogleAdsKit",
    platforms: [
        .iOS(.v17)
    ],
    products: [
        .library(
            name: "NnGoogleAdsKit",
            targets: ["NnGoogleAdsKit"]
        ),
        .library(
            name: "NnGoogleAdsUITestHelpers",
            targets: ["NnGoogleAdsUITestHelpers"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/nikolainobadi/NnTestKit.git", from: "2.0.0"),
        .package(url: "https://github.com/googleads/swift-package-manager-google-mobile-ads.git", from: "12.0.0")
    ],
    targets: [
        .target(
            name: "NnGoogleAdsKit",
            dependencies: [
                .product(name: "GoogleMobileAds", package: "swift-package-manager-google-mobile-ads")
            ]
        ),
        .target(
            name: "NnGoogleAdsUITestHelpers",
            linkerSettings: [
                .linkedFramework("XCTest")
            ]
        ),
        .testTarget(
            name: "NnGoogleAdsKitTests",
            dependencies: [
                "NnGoogleAdsKit",
                .product(name: "NnSwiftTestingHelpers", package: "NnTestKit"),
            ]
        )
    ]
)
