name: Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Display Xcode Version
        run: xcodebuild -version

      - name: Display Swift Version
        run: swift --version

      - name: Cache SwiftPM dependencies
        uses: actions/cache@v3
        with:
          path: |
            .build
            .swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Run Tests on iPhone 16
        run: |
          xcodebuild \
            -scheme NnGoogleAdsKit \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            test | xcpretty
